version: '2'

services:

  dependency-installer:
    build:
      context: .
      dockerfile: Dockerfile-dependency-installer
    volumes:
      - './my-project:/app'
    command: sh -c "composer install --ignore-platform-reqs"
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    depends_on:
      - dependency-installer
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
      - '3000:3000'
      - '5173:5173'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp

    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
      - dependency-installer
